# Generated by Django 4.2.2 on 2023-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('nearest_center', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('long_answer', 'Long Answer')], max_length=11)),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('long_answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('district_list', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=5)),
                ('phonenumber', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('schoolname', models.CharField(default='DPS', max_length=50)),
                ('schoolphone', models.CharField(max_length=50)),
                ('schoolemail', models.EmailField(max_length=254)),
                ('schooladdress', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(default='1', max_length=50)),
                ('pretest', models.CharField(default='-1', max_length=5)),
                ('posttest', models.CharField(default='-1', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=5)),
                ('phonenumber', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('schoolname', models.CharField(default='DPS', max_length=50)),
                ('schoolphone', models.CharField(max_length=50)),
                ('schoolemail', models.EmailField(max_length=254)),
                ('schooladdress', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(default='0', max_length=50)),
                ('pretest', models.CharField(default='-1', max_length=5)),
                ('posttest', models.CharField(default='-1', max_length=5)),
            ],
        ),
    ]
