# Generated by Django 4.2.2 on 2023-07-29 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('emailid_T1', models.EmailField(max_length=254)),
                ('emailid_T2', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('address', models.CharField(default='address', max_length=200)),
                ('datetime', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='session_attended',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.session'),
        ),
    ]
