# Generated by Django 4.2.2 on 2023-07-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_session_user_session_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
        ),
    ]
