# Generated by Django 4.2.2 on 2023-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_session_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
