# Generated by Django 4.2.2 on 2023-08-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_session_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
