# Generated by Django 4.2.2 on 2023-08-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questions_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='-1', max_length=50),
        ),
    ]
