# Generated by Django 4.2.2 on 2023-08-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_trainer_session_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnew',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
