# Generated by Django 4.2.2 on 2023-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_questionnew_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('option5', models.CharField(max_length=100)),
                ('option6', models.CharField(max_length=100)),
                ('correct', models.CharField(max_length=100)),
                ('language', models.CharField(default='English', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
