# Generated by Django 4.2.2 on 2023-10-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_questionshelp_delete_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionshelp',
            name='option5',
            field=models.CharField(max_length=1000),
        ),
    ]
